queries:
  sql_01: ../sql_queries

datasets:
  veh_data: https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/all-vehicles-model/exports/parquet?lang=en&timezone=America%2FGuatemala
  veh_data_schema: ../include/files/veh_data_schema.json

graphs_config:
  makers:
    color_discrete_sequence:
      - orange
   
    orientation: "h"
    
update_layout:
  general:
    paper_bgcolor: white #Background color inside the plot 
    plot_bgcolor: white # Background color around the plot
    margin: 
      l : 10 #left (in pixels)
      r : 10 #right
      t : 50 #top
      b : 10 #bottom
    xaxis:
      showgrid: False
    yaxis:
      showgrid: False
    title:
      font:
        family: Arial
        color: blue
        size: 12
        style: italic

  makers:
